### PR TITLE
image resizer and csv to excel added

### PR DESCRIPTION
**Pull request by Anuraj-IND**

### CODE REVIEW

**Review by PreyumKr — CHANGES_REQUESTED** [review]
Add their brief detail in the Main readme as well and maintain the lexical order of the titles. You can say there that for better clarity of use check the readme inside. But mention what their purpose and usecases are and modules that will be needed in the outer readme.

**Comment by Anuraj-IND** [comment]
> Add their brief detail in the Main readme as well and maintain the lexical order of the titles. You can say there that for better clarity of use check the readme inside. But mention what their purpose and usecases are and modules that will be needed in the outer readme.

ok i get it ill do it right away boss no worries

hacktoberfest-accepted (can you add this label too)

**Comment by Anuraj-IND** [comment]
is it fine now coz this way it looks more organised and easily accessible to the users so i followed the order and told there that there is already readme file there this way main readme file will not look messier?

**Comment by Anuraj-IND** [comment]
@PreyumKr respond it if you are active

**Review by PreyumKr — CHANGES_REQUESTED** [review]
The Headers are not in the Title format as the rest titles and you gave no brief details what the title's thing do in few lines.

**Comment by Anuraj-IND** [comment]
> The Headers are not in the Title format as the rest titles and you gave no brief details what the title's thing do in few lines.

@PreyumKr tell me file name and what I have to do now I saw some headings like that so I did like that

**Comment by PreyumKr** [comment]
> > The Headers are not in the Title format as the rest titles and you gave no brief details what the title's thing do in few lines.
> 
> @PreyumKr tell me file name and what I have to do now I saw some headings like that so I did like that

Add the Title with at least first word capital in major words and csv like CSV and I have no title in readme like that what you have written with all small words. Just search title format that's basically that only first word capital rest small unless its a useless word like on from the etc.. And in readme add something like This code will help you resize images from whatever size to whatever size. next point it contains xyz modules. next point for further details for implementation look inside the internal readme.
Same goes for the other, give some basic overview of the project.

**Comment by PreyumKr** [comment]
> > Add their brief detail in the Main readme as well and maintain the lexical order of the titles. You can say there that for better clarity of use check the readme inside. But mention what their purpose and usecases are and modules that will be needed in the outer readme.
> 
> ok i get it ill do it right away boss no worries
> 
> hacktoberfest-accepted (can you add this label too)

don't worry give it one last edit whatever ill merge and add the tag. Thats not really important. Any pr on hacktober labeled repo counts in your records.

**Comment by Anuraj-IND** [comment]
@PreyumKr sorry was i college that time now its fine ig?

**Review by PreyumKr — APPROVED** [review]
You still gave bigger markdown headers to titles below the main title of the project. I don't know how people can't see how other title and their descriptions are written. I am approving this one but won't approve any other until the format is ok

**Pull request merged**
